### ISSUE TITLE
inference real world low quality text image

### ISSUE THREAD

**Issue by zzksdu** [jdfxzzy/PEAN#12]
how to inference low quality text image without gt image simply?

i set param as flow:
--batch_size="32" --mask --rec="aster" --srb="1" --resume="./ckpt/PEAN_weights/PEAN_pretrained.pth" --pre_training --test --test_data_dir="my input folder"
dataset is set to lmdbDataset_realForTest

i get worse result.so can you help me fix the error?
@jdfxzzy

**Comment by jdfxzzy** [comment]
Our model supports inference low quality text image without GT image. However, our model was trained on the TextZoom benchmark, while your images might be completely different from these images in terms of style and blurring mode. Therefore, we cannot make sure the SR images have good quality.
