### ISSUE TITLE
请问一下作者的工作在test的时候是否也是将benchmark中的HR图片作为输入进行测试

### ISSUE THREAD

**Issue by 761qgmpgz943** [jdfxzzy/PEAN#3]

**Comment by jdfxzzy** [comment]
不需要的，请看论文中的Fig.2，HR图像那一路使用了蓝色箭头标识，这表明仅在训练阶段使用

**Comment by 761qgmpgz943** [comment]
直接使用命令：`python main.py --batch_size="32" --mask --rec="aster" --srb="1"`进行训练，到200 epoch 的时候的测试结果如下:

evaling easy
aster_accuray: 75.85% | crnn_accuray: 62.94% | moran_accuray: 73.93% 
best_easy_aster = 77.21%
best_easy_crnn = 64.85%
best_easy_moran = 75.11%

evaling medium
aster_accuray: 69.08% | crnn_accuray: 58.51% | moran_accuray: 68.38% 
best_medium_aster = 70.20%
best_medium_crnn = 59.37%
best_medium_moran = 68.75%

evaling hard
aster_accuray: 60.87% | crnn_accuray: 52.62% | moran_accuray: 60.39% 
best_hard_aster = 61.83%
best_hard_crnn = 53.12%
best_hard_moran = 60.92%

1. 这结果很差，是因为训练的epoch不够还是因为没有进行--pretrain所以导致准确率那么低的吗？
2. 请问--pretrain需要多少epoch，然后进行微调需要多少epoch呢
3. 请问一下使用--pretrain的时候出现如下报错该怎么解决？(因为我加了注释的缘故，所以报错行数应为仓库代码的第107行)
![image](https://github.com/user-attachments/assets/e3959ad4-20ae-4738-a3cb-38eafcec67ca)
![image](https://github.com/user-attachments/assets/e6789e85-0b6e-4b30-b44f-1967afc697b9)
恳求您的答复 @jdfxzzy

**Comment by jdfxzzy** [comment]
感谢您对该工作的欣赏和认可！以下是我对您的问题的解答：
1. 我个人认为您说的两个原因都存在，论文中也对不进行预训练的情况进行了实验，详见Table XIX，我认为您可以尝试进行预训练，或者增加训练轮数。并且，这与您使用的硬件设备，以及Python和Pytorch版本都有关。同时，您还要确保您使用了正确的SFM loss、PARSeq识别器。
2. 同上问题，我认为这与您使用的硬件设备，以及Python和Pytorch版本都有关。建议您至少尝试200~500轮。
3. 感谢您的反馈！经检查，这部分代码我少提交了一部分，我也已在仓库中进行更新，欢迎您再次尝试。

**Comment by 761qgmpgz943** [comment]
您好我使用环境和requirements.txt中的一致的情况下遇到了个问题：

1. 使用下载的权重在测试的时候发现aster测试结果低一些，crnn和moran没有发现异常

loading PEAN (w/o TPEM) from ./saved_model/PEAN_final.pth 
loading TPEM from /share/codes/lll/text/PEAN_last/saved_model/TPEM_final.pth
evaling /share/codes/lll/text/text_diffusion_small/textRoom/easy
loading pretrained parseq model from /share/codes/lll/text/parseq-main/parseq-bb5792a6.pt
loading pretrained aster model from /share/datasets/TextZoom/models/aster.pth.tar

{'accuracy': {'/share/codes/lll/text/text_diffusion_small/textRoom/easy': 0.8166}, 'psnr_avg': 23.686811, 'ssim_avg': 0.864549, 'fps': 15.519645068740688}

{'accuracy': {'/share/codes/lll/text/text_diffusion_small/textRoom/medium': 0.6867}, 'psnr_avg': 19.489105, 'ssim_avg': 0.680274, 'fps': 15.74897072412681}

{'accuracy': {'/share/codes/lll/text/text_diffusion_small/textRoom/hard': 0.4981}, 'psnr_avg': 20.131577, 'ssim_avg': 0.729712, 'fps': 16.631027902552596} @jdfxzzy

**Comment by jdfxzzy** [comment]
您好，首先，您使用CRNN和MORAN进行测试，发现结果一致，说明我们提供的权重文件是没有问题的。对于ASTER识别器下的准确率，我也发现在不同设备上测试时，会出现准确率有些许差异的情况。我们论文里面汇报的结果是在实验室计算集群上测试的（CentOS系统），我在将代码上传到本仓库前，在本地的windows系统上测试过，easy子集上的结果大约为83左右，确实有些许降低。我个人认为您无需过于纠结于此问题，因为这可能是因为硬件、随机数等外部原因导致的。

**Comment by 761qgmpgz943** [comment]
结果无法复现，根据提供的pretrain模型测试的结果为：
evaling easy
[2024-08-29 11:58:05] | PSNR 23.60 | SSIM 0.8567
aster_accuray: 88.20% | crnn_accuray: 74.68% | moran_accuray: 85.11% 

evaling medium
[2024-08-29 12:03:22] | PSNR 19.61 | SSIM 0.6767

aster_accuray: 75.41% | crnn_accuray: 67.33% | moran_accuray: 72.79% 

evaling hard
[2024-08-29 12:08:18] | PSNR 20.03 | SSIM 0.7133
aster_accuray: 61.28% | crnn_accuray: 54.95% | moran_accuray: 57.56% 


我在本地环境 seed gpu型号一样的情况下无法达到88%多的准确率，而且差的也不是一点半点
![image](https://github.com/user-attachments/assets/fbe53963-5303-40e4-897b-6f4727ad35b8)

**Comment by 761qgmpgz943** [comment]
咋关闭了？
