### ISSUE TITLE
Pretrained weight? Inference code? Project setup?

### ISSUE THREAD

**Issue by abghaky** [jdfxzzy/PEAN#4]
Hi
I am trying to run inference using the model on some text data. But I have three issues:

1- The pretrained weights on Google Drive require access permission. I requested access, but didn't receive it yet.
2- I am not sure how to have a simple script for inference, because several models are being used for various tasks and the setup process  looks very convoluted to me. Is it possible to have a simple inference script for inference? 
3- It is not obvious, at least to me, what files from other repositories/models need to be placed where within the folder structure to run the inference. Is it possible to have a section with step-by-step explanation for simple inference?

Any help is appreciated.

**Comment by jdfxzzy** [comment]
Thank you for your appreciation to our work.
1. I am sorry that there are something wrong with the access authority of the Google Drive link. I have fixed it and now everyone on the Internet can have access to our model. You can have another try.
2. I think the steps listed in the README.md is simple enough. You only need to change the path of the trained models, and use the provided script to start the inference phase.
3. If you only need to run the inference phase, firstly you should download the "parseq-bb5792a6.pt" from the PARSeq repositories. Following previous works, weights of ASTER, CRNN and MORAN are also needed to start the evaluation process. These weights can be put in any folder you like. You only need to change the path in the ./config/super_resolution.yaml file.

**Comment by abghaky** [comment]
Thank you for providing the models. 
Is there any way to download "pretrain_transformer_stroke_decomposition.pth" file without need to create account on Baidu? I am not located in China

**Comment by jdfxzzy** [comment]
I think maybe you can try to contact the authors of the paper "Text Gestalt: Stroke-Aware Scene Text Image Super-Resolution" and ask them to send it to you. It is not our work, so I think it is inappropriate to directly send it to you here.
