### ISSUE TITLE
关于训练模型的问题

### ISSUE THREAD

**Issue by 02w20** [jdfxzzy/PEAN#5]
您好！

我注意到在super_resolution.yaml中的训练轮次是42000，我有几个问题希望可以帮忙解答，十分感谢！

①为什么需要这么大的训练轮次呢，和diffusion有关吗？

②在预训练和微调中的训练轮次均为42000吗？

③请问您用了什么设备，训练时间大概是多少？

非常期待您的解答，谢谢！

**Comment by jdfxzzy** [comment]
您好，感谢您对本工作的关注！该文件中的训练轮数设为42000，仅仅是因为我此前关注到[该issue](https://github.com/WenjiaWang0312/TextZoom/issues/8#issuecomment-767552860)中的网友，训练了42000轮才得到了一个较好的TSRN模型，因此我将这里设为42000，实际上完全不需要这么多轮次，您也可以在您认为训练完毕以后及时停止。我使用的设备是实验室计算集群，配备CentOS系统和TITAN RTX显卡。由于时间过于久远，具体训练时间我记不清了，我认为您训练200~500轮应该可以得到一个较为满意的结果。
