### ISSUE TITLE
关于模型训练的问题

### ISSUE THREAD

**Issue by 02w20** [jdfxzzy/PEAN#6]
你好，我在训练模型时遇到了这个问题，请问可以提供一下这个文本文件吗？十分感谢
File "/home/PEAN/interfaces/super_resolution.py", line 22, in train
model_dict = self.generator_init()
File "/home/PEAN/interfaces/base.py", line 125, in generator_init
image_crit = stroke_focus_loss.StrokeFocusLoss(self.args)
File "/home/PEAN/loss/stroke_focus_loss.py", line 26, in init
stroke_decompose_lines = open('./english_decomposition.txt', 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: './english_decomposition.txt'

**Comment by jdfxzzy** [comment]
您好，这个文件来自于前人工作：[https://github.com/FudanVI/FudanOCR/tree/main/text-gestalt.](https://github.com/FudanVI/FudanOCR/tree/main/text-gestalt)，您可自行前往其第二个（Datasets）的百度云链接下载。

**Comment by 02w20** [comment]
您好，上面的问题已经解决了，十分感谢！

但是在您给出的parseq链接中https://github.com/baudm/parseq          ，我并没有找到对应的.pt文件的下载链接，请问可以具体指出一下吗？谢谢！

**Comment by jdfxzzy** [comment]
![image](https://github.com/user-attachments/assets/ee62a98e-fb3c-487c-908f-f348e8e06cba)

**Comment by 02w20** [comment]
你好，我在训练模型过程中每经历320iter去eval时遇到了这个报错（图一），我想知道该如何修改它，谢谢！
`  File "/home/PEAN/main.py", line 23, in main
    Mission.train() 
  File "/home/PEAN/interfaces/super_resolution.py", line 141, in train
    metrics_dict = self.eval(model, val_loader, epoch, parseq)
  File "/home/PEAN/interfaces/super_resolution.py", line 273, in eval
    images_hr, images_lr, label_strs, _ = data
ValueError: too many values to unpack (expected 4)`

我用调试去得到了此刻有关data的内容，但不太会修改，请给出一点建议，谢谢！
![NW%~TW3 )322TB$0UQ@AK4U](https://github.com/user-attachments/assets/0dee7ce6-7c19-454f-bd94-4af8753be022)

**Comment by 02w20** [comment]
我仿照TATT的代码，修改了get_val_data和get_test_data函数，解决了前面提出的问题。

**Comment by jdfxzzy** [comment]
刚刚看到，解决了就好

**Comment by NorakneaTh** [comment]
> 我仿照TATT的代码，修改了get_val_data和get_test_data函数，解决了前面提出的问题。

currently, I'm facing the same problems. Would you mind sharing the solution that work for you?
I have try the method from TATT but it stil get the same error for me

**Comment by xiao202111** [comment]
> > 我仿照TATT的代码，修改了get_val_data和get_test_data函数，解决了前面提出的问题。
> 
> currently, I'm facing the same problems. Would you mind sharing the solution that work for you? I have try the method from TATT but it stil get the same error for me

you can look at #11 issue
