### ISSUE TITLE
关于模型测试的问题

### ISSUE THREAD

**Issue by 02w20** [jdfxzzy/PEAN#7]
您好！我已经下载了您提供的权重文件，但在输入命令行“python main.py --batch_size="32" --mask --rec="aster" --srb="1" --resume="./ckpt/PEAN_final.pth" --test （测试数据的路径在main.py中已修改）”后发现数据结果不太对，我观察到"loading PEAN (w/o TPEM) from ./ckpt/PEAN_final.pth"后没有出现loading TPEM这句提示语。因此，我分析其中一个原因是，没有正确加载TPEM的权重，我已经cfg_diff_prior.json中修改了resume_state的值，
![image](https://github.com/user-attachments/assets/425eb327-33f1-4a80-ae14-d3ae563a5aa5)，请问可能是哪里出现了问题？

我在全局搜索时查找到了loading TPEM这句话是在model.py中，然后我自行添加了else分支，发现仍无任何输出。
![image](https://github.com/user-attachments/assets/15abfe8c-d39d-4900-9415-4294cf852612)

感谢您的回复！

**Comment by ych-tju** [comment]
您好，我也遇到了这个问题，请问您是怎么解决的？

**Comment by Massif0422** [comment]
我也是这情况，请问解决了吗
